// Generates docs/use-case-coverage.md (and prints it) from src/lib/capabilities' aggregated
// use-case list — the master backlog (implemented or not), so a use case with no code yet still
// shows up as "not started" instead of silently disappearing from the report. See
// docs/architecture.md for the model this reports against.
import fs from 'node:fs';
import path from 'node:path';
import { getAllUseCases, type FlatUseCaseEntry } from '../src/lib/capabilities';

const CAPABILITIES_DIR = path.resolve(__dirname, '../src/lib/capabilities');
const TRACEABILITY_DOC = path.resolve(__dirname, '../docs/d6.4-requirements-traceability.md');
const OUTPUT_DOC = path.resolve(__dirname, '../docs/use-case-coverage.md');

type Status = 'not started' | 'implemented, untested' | 'verified';

async function statusFor(entry: FlatUseCaseEntry): Promise<Status> {
  if (!entry.module) return 'not started';

  const modulePath = path.join(CAPABILITIES_DIR, entry.capabilityId, entry.module);
  try {
    await import(`${modulePath}.ts`);
  } catch {
    return 'not started';
  }

  return fs.existsSync(`${modulePath}.test.ts`) ? 'verified' : 'implemented, untested';
}

function loadRequirementIds(): Set<string> {
  const text = fs.readFileSync(TRACEABILITY_DOC, 'utf8');
  const ids = new Set<string>();
  for (const match of text.matchAll(/^\|\s*(R\d+(?:\.\d+){1,3}(?:\s*\([ab]\))?)\s*\|/gm)) {
    ids.add(match[1].replace(/\s*\([ab]\)/, ''));
  }
  return ids;
}

async function main() {
  const knownRequirementIds = loadRequirementIds();
  const entries = getAllUseCases();
  const statuses = await Promise.all(entries.map(async (entry) => ({ entry, status: await statusFor(entry) })));
  statuses.sort((a, b) => a.entry.capabilityName.localeCompare(b.entry.capabilityName) || a.entry.id.localeCompare(b.entry.id));

  for (const { entry } of statuses) {
    const unknownIds = entry.satisfies.filter((id) => !knownRequirementIds.has(id));
    if (unknownIds.length) {
      console.warn(`WARNING: ${entry.id} references unknown requirement id(s): ${unknownIds.join(', ')}`);
    }
  }

  const byRequirement = new Map<string, { useCaseIds: string[]; verified: boolean }>();
  for (const { entry, status } of statuses) {
    for (const reqId of entry.satisfies) {
      const row = byRequirement.get(reqId) ?? { useCaseIds: [], verified: false };
      row.useCaseIds.push(entry.id);
      row.verified = row.verified || status === 'verified';
      byRequirement.set(reqId, row);
    }
  }

  const notStarted = statuses.filter((s) => s.status === 'not started').length;
  const untested = statuses.filter((s) => s.status === 'implemented, untested').length;
  const verified = statuses.filter((s) => s.status === 'verified').length;

  const useCaseRows = statuses
    .map(({ entry, status }) => `| ${entry.capabilityName} | ${entry.id} | ${entry.satisfies.join(', ') || '—'} | ${status} |`)
    .join('\n');

  const requirementRows = [...byRequirement.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([reqId, row]) => `| ${reqId} | ${row.useCaseIds.join(', ')} | ${row.verified ? 'yes' : 'no'} |`)
    .join('\n');

  const markdown = `# Use-case & requirements coverage

_Generated by \`npm run requirements:coverage\` — do not edit by hand._

Reports *verification* coverage (is there a test that would fail if the behavior broke) for every
use case registered under \`src/lib/capabilities/<name>/registry.ts\`, against the D6.4 \`Rx.x.x\`
requirement IDs it claims to satisfy. A use case with no code yet still shows up as **not started**
rather than disappearing — this is the literal backlog. Distinct from
[\`d6.4-requirements-traceability.md\`](./d6.4-requirements-traceability.md)'s own ✅/◑/✗/⏳/—
*implementation* status, which stays a human judgment call this script doesn't touch.

## Use-case view (grouped by capability)

| Capability | Use case | Requirements | Status |
|---|---|---|---|
${useCaseRows}

## Requirement view

_Only requirements claimed by at least one use case._

| Requirement | Use case(s) | Verified |
|---|---|---|
${requirementRows}

**Summary:** ${verified} verified, ${untested} implemented but untested, ${notStarted} not started (of ${statuses.length} total).
`;
  fs.writeFileSync(OUTPUT_DOC, markdown);
  console.log(markdown);
  console.log(`Written to ${path.relative(path.resolve(__dirname, '..'), OUTPUT_DOC)}`);
}

main();
