// Generates docs/use-case-coverage.md (and prints it) from use-cases/registry.ts — the central,
// flat backlog of every identified use case, implemented or not, so one with no code yet still
// shows up as "not started" instead of disappearing. See docs/architecture.md for the model this
// reports against: capability organizes the code (src/lib/capabilities/<name>/), this registry
// organizes testing/requirement-traceability, and the two don't need to share a physical shape.
import fs from 'node:fs';
import path from 'node:path';
import { useCaseRegistry } from '../use-cases/registry';
import { capabilities } from '../use-cases/capabilities';
import type { UseCaseEntry } from '../use-cases/types';

const SRC_CAPABILITIES_DIR = path.resolve(__dirname, '../src/lib/capabilities');
const TRACEABILITY_DOC = path.resolve(__dirname, '../docs/d6.4-requirements-traceability.md');
const OUTPUT_DOC = path.resolve(__dirname, '../docs/use-case-coverage.md');

const capabilityNames = new Map(capabilities.map((c) => [c.id, c.name]));

type Status = 'not started' | 'implemented, untested' | 'verified';

async function statusFor(entry: UseCaseEntry): Promise<Status> {
  if (!entry.module) return 'not started';

  const modulePath = path.join(SRC_CAPABILITIES_DIR, entry.capability, entry.module);
  try {
    await import(`${modulePath}.ts`);
  } catch {
    return 'not started';
  }

  return fs.existsSync(`${modulePath}.test.ts`) ? 'verified' : 'implemented, untested';
}

function loadRequirementIds(): Set<string> {
  const text = fs.readFileSync(TRACEABILITY_DOC, 'utf8');
  const ids = new Set<string>();
  for (const match of text.matchAll(/^\|\s*(R\d+(?:\.\d+){1,3}(?:\s*\([ab]\))?)\s*\|/gm)) {
    ids.add(match[1].replace(/\s*\([ab]\)/, ''));
  }
  return ids;
}

async function main() {
  const knownRequirementIds = loadRequirementIds();
  const statuses = await Promise.all(useCaseRegistry.map(async (entry) => ({ entry, status: await statusFor(entry) })));
  statuses.sort(
    (a, b) =>
      (capabilityNames.get(a.entry.capability) ?? a.entry.capability).localeCompare(capabilityNames.get(b.entry.capability) ?? b.entry.capability) ||
      a.entry.id.localeCompare(b.entry.id),
  );

  for (const { entry } of statuses) {
    if (!capabilityNames.has(entry.capability)) {
      console.warn(`WARNING: ${entry.id} references unknown capability id: ${entry.capability}`);
    }
    const unknownIds = entry.satisfies.filter((id) => !knownRequirementIds.has(id));
    if (unknownIds.length) {
      console.warn(`WARNING: ${entry.id} references unknown requirement id(s): ${unknownIds.join(', ')}`);
    }
  }

  const byRequirement = new Map<string, { useCaseIds: string[]; verified: boolean }>();
  for (const { entry, status } of statuses) {
    for (const reqId of entry.satisfies) {
      const row = byRequirement.get(reqId) ?? { useCaseIds: [], verified: false };
      row.useCaseIds.push(entry.id);
      row.verified = row.verified || status === 'verified';
      byRequirement.set(reqId, row);
    }
  }

  const notStarted = statuses.filter((s) => s.status === 'not started').length;
  const untested = statuses.filter((s) => s.status === 'implemented, untested').length;
  const verified = statuses.filter((s) => s.status === 'verified').length;

  const useCaseRows = statuses
    .map(({ entry, status }) => {
      const capabilityName = capabilityNames.get(entry.capability) ?? entry.capability;
      return `| ${capabilityName} | ${entry.id} | ${entry.satisfies.join(', ') || '—'} | ${status} |`;
    })
    .join('\n');

  const requirementRows = [...byRequirement.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([reqId, row]) => `| ${reqId} | ${row.useCaseIds.join(', ')} | ${row.verified ? 'yes' : 'no'} |`)
    .join('\n');

  const markdown = `# Use-case & requirements coverage

_Generated by \`npm run requirements:coverage\` — do not edit by hand._

Reports *verification* coverage (is there a test that would fail if the behavior broke) for every
use case in [\`use-cases/registry.ts\`](../use-cases/registry.ts) — the central backlog, implemented
or not — against the D6.4 \`Rx.x.x\` requirement IDs it claims to satisfy. A use case with no code
yet still shows up as **not started** rather than disappearing — this is the literal backlog.
Distinct from [\`d6.4-requirements-traceability.md\`](./d6.4-requirements-traceability.md)'s own
✅/◑/✗/⏳/— *implementation* status, which stays a human judgment call this script doesn't touch.

## Use-case view (grouped by capability)

| Capability | Use case | Requirements | Status |
|---|---|---|---|
${useCaseRows}

## Requirement view

_Only requirements claimed by at least one use case._

| Requirement | Use case(s) | Verified |
|---|---|---|
${requirementRows}

**Summary:** ${verified} verified, ${untested} implemented but untested, ${notStarted} not started (of ${statuses.length} total).
`;

  fs.writeFileSync(OUTPUT_DOC, markdown);
  console.log(markdown);
  console.log(`Written to ${path.relative(path.resolve(__dirname, '..'), OUTPUT_DOC)}`);
}

main();
