import type { UseCaseEntry } from './types';

// The central, flat backlog of every identified use case — implemented or not. capability is a
// plain tag here (not a folder): src/lib/capabilities/<name>/ organizes the code, this registry
// organizes testing/requirement-traceability. See docs/architecture.md.
export const useCaseRegistry: UseCaseEntry[] = [
  {
    id: 'complete-pre-screening-check',
    name: 'Complete pre-screening check',
    capability: 'application-lifecycle',
    satisfies: ['R7.2.1', 'R7.2.2', 'R7.2.4', 'R7.2.6'],
    module: './checklist-checks',
  },
  {
    id: 'complete-substantive-assessment',
    name: 'Complete substantive assessment',
    capability: 'application-lifecycle',
    satisfies: ['R7.3.1', 'R7.3.3', 'R7.3.4', 'R7.3.7'],
    module: './checklist-checks',
  },
  { id: 'submit-application', name: 'Submit application', capability: 'application-lifecycle', satisfies: [], module: null },
  {
    id: 'request-additional-information',
    name: 'Request additional information',
    capability: 'application-lifecycle',
    satisfies: [],
    module: null,
  },
  {
    id: 'resume-processing',
    name: 'Resume processing after additional info received',
    capability: 'application-lifecycle',
    satisfies: [],
    module: null,
  },
  {
    id: 'extend-decision-deadline',
    name: 'Extend the decision deadline',
    capability: 'application-lifecycle',
    satisfies: [],
    module: null,
  },
  { id: 'issue-decision', name: 'Issue decision (positive/negative)', capability: 'application-lifecycle', satisfies: [], module: null },
  { id: 'withdraw-application', name: 'Withdraw application', capability: 'application-lifecycle', satisfies: [], module: null },
  {
    id: 'assign-trusted-data-holder',
    name: 'Assign a trusted data holder',
    capability: 'application-lifecycle',
    satisfies: [],
    module: null,
  },
  { id: 'create-fee-estimate', name: 'Create a fee estimate', capability: 'fee-invoicing', satisfies: [], module: null },
  { id: 'decide-fee-estimate', name: 'Accept/reject a fee estimate', capability: 'fee-invoicing', satisfies: [], module: null },
  { id: 'generate-provisional-invoice', name: 'Generate a provisional invoice', capability: 'fee-invoicing', satisfies: [], module: null },
  { id: 'issue-permit-invoice', name: 'Issue a permit invoice', capability: 'fee-invoicing', satisfies: [], module: null },
  { id: 'update-invoice-status', name: 'Update invoice/payment status', capability: 'fee-invoicing', satisfies: [], module: null },
  { id: 'issue-initial-permit', name: 'Issue initial permit', capability: 'permit-lifecycle', satisfies: [], module: null },
  {
    id: 'request-permit-change',
    name: 'Request a permit change (amendment/renewal/revocation-appeal)',
    capability: 'permit-lifecycle',
    satisfies: [],
    module: null,
  },
  { id: 'approve-permit-change', name: 'Approve a permit change request', capability: 'permit-lifecycle', satisfies: [], module: null },
  { id: 'reject-permit-change', name: 'Reject a permit change request', capability: 'permit-lifecycle', satisfies: [], module: null },
  { id: 'activate-permit-version', name: 'Activate a permit version', capability: 'permit-lifecycle', satisfies: [], module: null },
  { id: 'provision-spe', name: 'Provision/deprovision an SPE for a permit', capability: 'permit-lifecycle', satisfies: [], module: null },
  { id: 'file-appeal', name: 'File an appeal against a decision', capability: 'appeals', satisfies: [], module: null },
  { id: 'decide-appeal', name: 'Decide an appeal', capability: 'appeals', satisfies: [], module: null },
  { id: 'attach-appeal-document', name: 'Attach supporting documents to an appeal', capability: 'appeals', satisfies: [], module: null },
  {
    id: 'request-data-extraction',
    name: 'Request a data extraction against a permit',
    capability: 'data-access-execution',
    satisfies: [],
    module: null,
  },
  {
    id: 'decide-extraction-request',
    name: 'Approve/reject an extraction request',
    capability: 'data-access-execution',
    satisfies: [],
    module: null,
  },
  {
    id: 'import-ncp-application',
    name: 'Import an application from the NCP queue',
    capability: 'external-ingestion',
    satisfies: [],
    module: null,
  },
  { id: 'import-hdeu-payload', name: 'Import an HDEU payload', capability: 'external-ingestion', satisfies: [], module: null },
];
